
set ( _PACKAGE_ZIP_WORKDIR ${CMAKE_BINARY_DIR}/pack/zip)
set ( _PACKAGE_TARGET package_${PACKAGE_${PROJECT_NAME}_NAME})

add_custom_target(${_PACKAGE_TARGET}
	COMMENT "Creating zip archive: ${PACKAGE_${PROJECT_NAME}_FILENAME}.zip"
	COMMAND ${CMAKE_COMMAND} --install . --component ${PROJECT_NAME} --prefix "${_PACKAGE_ZIP_WORKDIR}/${PACKAGE_${PROJECT_NAME}_FILENAME}"
	COMMAND ${CMAKE_COMMAND}
		-E chdir ${_PACKAGE_ZIP_WORKDIR} ${CMAKE_COMMAND}
		-E tar c "${CMAKE_BINARY_DIR}/${PACKAGE_${PROJECT_NAME}_FILENAME}.zip" --format=zip "${PACKAGE_${PROJECT_NAME}_FILENAME}"
	WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
)
